version: 1
formatters:
  default:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(lineno)d - %(message)s"

handlers:
  file:
    class: logging.FileHandler
    filename: logs/app.log
    formatter: default
loggers:
  uvicorns: 
    handlers: [file]
    level: INFO
  uvicorns.error:
    handlers: [file]
    level: INFO
  uvicorns.access:
    handlers: [file]
    level: INFO
root:
  handlers: [file]
  level: INFO